services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=dev_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=bookkeeper'
    ports:
      - '4321:5432'
    volumes:
      - ./init_bookkeeper_gen.sql:/docker-entrypoint-initdb.d/init_bookkeeper_gen.sql:Z
